### ISSUE TITLE
[disclaimer] It won't boost your app

### ISSUE THREAD

**Issue by brunoandradebr** [jagenjo/Canvas2DtoWebGL#14]
If you got here and think it will boost your 2d context it won't. Cloning and changing **render_benchmark_fillRect** example to iterate over **10000** instead of **1000**, 2d context handles better then using webgl. There is no dreaming 2d api to perform like gpu rendering - sad =/

```
// modified example from this repo
function render_benchmark_fillRect(canvas, ctx) {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    for (var i = 0; i < 10000; i++) {
        ctx.fillRect(500, 500, 2, 2);
    }
}
```

**Comment by jagenjo** [comment]
it wont because canvas2D is already GPU accelerated, internally browsers use the GPU.

The only place where using WebGL could be faster than using the Canvas2D is if you make use of big images (because canvas2D tries to preserve as much fidelity to the image while WebGL uses mipmaps).

The idea of Canvas2DtoWebGL is not to be faster, is to help you mix 2D and 3D easily in the same Canvas, and adding some missing features to Canvas2D. You can even render a Canvas2D in a 3D space if you want.

**Comment by brunoandradebr** [comment]
**"The idea of Canvas2DtoWebGL is not to be faster, is to help you mix 2D and 3D easily in the same Canvas"**

It's what I got only when tried. And I opened this off-topic as disclaimer to everyone like me that didn't realise it's purpose at first look.  I'm diving into webgl right now, feeling all the pain but it will be rewarding. My dream is to be as good as you :D 

Congrats for your work! i'm a big fan!
