### ISSUE TITLE
performance and color?

### ISSUE THREAD

**Issue by lidaof** [jagenjo/Canvas2DtoWebGL#9]
Hi Javi,

I am trying to use this library in my project for drawing canvas.
I noticed the drawing speed is actually slower than 2d canvas. Am I doing something wrong? or this library is not suitable for my purpose?
Thank you.

**Comment by jagenjo** [comment]
this library is not supposed to be faster. Current Canvas2D implementations already use the GPU and because they are implemented natively the performance is always faster.

The reason to use Canvas2DtoWebGL is if you want to mix 3D content with 2D content in the same canvas. Otherwise there is no benefit.

**Comment by lidaof** [comment]
i see. thanks for explanation.
